---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Toot Toot
- type: directory
  path: docs
  label: Pages
  create: all
  match: "*"
- type: heading
  label: Internal
- type: directory
  path: docs/team
  label: Team
  create: all
  match: "*"
  templates:
  - person

upload_dir: docs/.vuepress/public/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
